#!/bin/sh
#
# Start hostapd. Do this before bringing up wlan0.

case "$1" in
start)
	echo "Starting hostapd"
	hostapd -B /etc/hostapd.conf
	;;
stop)
	echo "Stopping hostapd"
	killall hostapd
	;;
restart|reload)
	"$0" stop
	"$0" start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
